feat: oAuth login
Kernel360/F2_PLAY_BADMINTON_BE pull request #24
Opened 2024-09-17 04:43 UTC by I-migi

## PR에 대한 설명 🔍

Spring Security를 사용해서 Jwt 방식의 OAuth 2.0 로그인을 구현했습니다

## 변경된 사항 📝

- MemberEntity 구현
- Spring Security 및 Jwt 설정 구현
- Google, Naver, Kakao OAuthResponse 및 OAuth 2.0 설정
- logout 기능 구현

## PR에서 중점적으로 확인되어야 하는 사항

EndPoint
- Login
    - Naver: /oauth2/authorization/naver [GET]
    - Google: /oauth2/authorization/google [GET]
    - Kakao: /oauth2/authorization/kakao [GET]
- Logout: /api/logout [POST]

2024-09-17 08:38 UTC, soeunnPark reviewed
수고하셨습니다 ~! 😊

2024-09-17 08:38 UTC, soeunnPark commented on badminton-api/src/main/resources/application.properties
> +spring.application.name=badminton-api
이 코드는 왜 필요한지 궁금합니다💭  `spring.application.name=badminton-api`

2024-09-17 08:38 UTC, soeunnPark commented on badminton-domain/src/main/java/org/badminton/domain/config/SecurityConfig.java
> +					configuration.setAllowedOrigins(Collections.singletonList("http://localhost:3000"));
8080 대신 3000을 쓰는 건가요?

2024-09-17 08:38 UTC, soeunnPark commented on badminton-domain/src/main/java/org/badminton/domain/config/SecurityConfig.java
> +		http
http 매번 안쓰고 . 으로 계속 연결해서 설정할 수 있어요!

2024-09-17 08:38 UTC, soeunnPark commented on badminton-api/src/main/java/org/badminton/api/BadmintonApplication.java
> +@ComponentScan(basePackages = {"org.badminton.api", "org.badminton.domain"})
이거 Jpa Config에 있어서 빼고 올려주세요!

2024-09-17 08:38 UTC, soeunnPark commented on badminton-api/src/main/java/org/badminton/api/member/MemberController.java
> +		if (request.getSession(false) != null) {
session에서는 어떤걸 삭제하는 걸까요?

2024-09-17 08:38 UTC, soeunnPark commented on badminton-domain/build.gradle
> +    implementation group: 'org.springdoc', name: 'springdoc-openapi-starter-webmvc-ui', version: '2.6.0'
swagger는 api 쪽 모듈에서만 사용하지 않나요?

2024-09-17 08:38 UTC, soeunnPark commented on badminton-domain/src/main/java/org/badminton/domain/config/SecurityConfig.java
> +@ComponentScan(basePackages = "org.badminton.domain")
security config 파일은 어느 모듈에 둬야 할지 이야기해봐야 할 것 같아요. http 요청을 처리하는 api 모듈  쪽에 두는 것이 더 좋을 것 같습니다!

2024-09-17 08:38 UTC, soeunnPark commented on badminton-domain/src/main/java/org/badminton/domain/member/jwt/JwtFilter.java
> +	protected boolean shouldNotFilter(HttpServletRequest request) throws ServletException {
shouldNotFilter 사용하는거 좋아요! 👍

2024-09-17 08:38 UTC, soeunnPark commented on badminton-domain/src/main/java/org/badminton/domain/member/jwt/JwtFilter.java
> +			System.out.println("token expired");
sout -> log로 변경하면 좋을 것 같습니다 😄

2024-09-17 09:34 UTC, I-migi commented on badminton-api/src/main/resources/application.properties
> +spring.application.name=badminton-api
없어도 코드 실행에 문제는 없는거로 아는데 각 모듈 안의 application.properties에 어떤 모듈의 application.properties인지 표시해놓으면 더 좋을 것 같아서 추가했습니다 😄

2024-09-17 09:35 UTC, I-migi commented on badminton-domain/src/main/java/org/badminton/domain/config/SecurityConfig.java
> +					configuration.setAllowedOrigins(Collections.singletonList("http://localhost:3000"));
리액트와 함께 사용하려면 3000을 써야 해서 작성했습니다!

2024-09-17 09:35 UTC, I-migi commented on badminton-domain/src/main/java/org/badminton/domain/config/SecurityConfig.java
> +		http
http로 하는게 가독성이 더 좋아보여서 작성했는데 목요일날 대화해보고 수정하겠습니다!

2024-09-17 09:36 UTC, I-migi commented on badminton-domain/build.gradle
> +    implementation group: 'org.springdoc', name: 'springdoc-openapi-starter-webmvc-ui', version: '2.6.0'
MemberEntity의 필드에 @Schema를 사용하려면 필요해서 추가했습니다

2024-09-17 09:36 UTC, I-migi commented on badminton-domain/src/main/java/org/badminton/domain/config/SecurityConfig.java
> +@ComponentScan(basePackages = "org.badminton.domain")
네네 목요일날 대화해보고 결정해보도록 해요!!

2024-09-17 09:37 UTC, I-migi commented on badminton-domain/src/main/java/org/badminton/domain/member/jwt/JwtFilter.java
> +			System.out.println("token expired");
네네 감사합니다

2024-09-17 09:38 UTC, I-migi commented on badminton-api/src/main/java/org/badminton/api/member/MemberController.java
> +		if (request.getSession(false) != null) {
저희는 session을 사용하지 않는데 JSessionId가 쿠키에 생성이 되어서 JSessionId를 삭제하기 위해서 추가했습니다
JSessionId가 계속 생성되는 이유는 추가로 알아봐야할 것 같아요!

2024-09-17 09:40 UTC, I-migi commented on badminton-api/src/main/java/org/badminton/api/BadmintonApplication.java
> +@ComponentScan(basePackages = {"org.badminton.api", "org.badminton.domain"})
ComponentScan 어노테이션을 제거하니깐 badminton-domain의 서비스를 인식 못해서 추가했습니다
Jpa Config에 추가했는데도 안되는 이유는 추가로 알아봐야 할 것 같아요

2024-09-17 11:23 UTC, soeunnPark commented on badminton-domain/src/main/java/org/badminton/domain/config/SecurityConfig.java
> +@ComponentScan(basePackages = "org.badminton.domain")
@I-migi domain 에 있어야 할 이유가 따로 있는 걸까요?

2024-09-17 11:48 UTC, km2535 requested changes
리뷰 내용들 확인하고 병합하는 것이 좋을 듯합니다.

2024-09-17 13:50 UTC, I-migi commented on badminton-api/src/main/java/org/badminton/api/member/MemberController.java
> +		if (request.getSession(false) != null) {
시큐리티에서 기본적으로 제공하는 로그아웃 기능은 session을 사용한 로그인일 때 적용되는 것으로 알고 있어요!

2024-09-18 04:44 UTC, LichKing-lee commented on badminton-api/src/main/java/org/badminton/api/config/security/SecurityConfig.java
> +@ComponentScan(basePackages = "org.badminton.domain")
컴포넌트 스캔이 여기저기 산발적으로 나오네요 소은님 PR 에서도 코멘트드리긴했는데 그냥 최상위에서 `org.badminton` 패키지로 스캔하는게 낫겠어요

2024-09-19 03:39 UTC, km2535 approved these changes
확인 완료하였습니다.

2024-09-19 03:39 UTC, merged