feat: Make list
Kernel360/F2_PLAY_BADMINTON_BE pull request #266
Opened 2024-11-01 08:21 UTC by I-migi

## PR에 대한 설명 🔍

https://github.com/Kernel360/F2_PLAY_BADMINTON_BE/issues/263#issue-2628181839

## 변경된 사항 📝

<img width="685" alt="image" src="https://github.com/user-attachments/assets/88b8ec7c-53be-4296-a12b-cc34e020d303">

<img width="1390" alt="image" src="https://github.com/user-attachments/assets/79211623-9fa5-4b37-a390-6e728fc4e53f">

2024-11-01 08:29 UTC, km2535 approved these changes
PR 리뷰 내용 관련 수정해주시고 머지 해주세용

2024-11-01 08:29 UTC, km2535 commented on api/src/main/java/org/badminton/api/interfaces/club/dto/ClubApplicantResponse.java
> +	public static ClubApplicantResponse fromClubApply(ClubApply clubApply) {
fromClubApply --> from 으로 변경해주세요 이미 매개변수에서 전달하고자 하는 의미가 있습니다.

2024-11-01 08:29 UTC, km2535 commented on api/src/main/java/org/badminton/api/interfaces/member/dto/MemberMyPageResponse.java
> +				: null;
null 로 리턴을 하는 것 보다 데이터 없다면 Exception이나 빈 객체를 전달하는 것이 좋을 것 같습니당

2024-11-01 08:33 UTC, soeunnPark requested changes

2024-11-01 08:33 UTC, soeunnPark commented on api/src/main/java/org/badminton/api/application/club/ClubFacade.java
> +	public List<ClubApply> readClubApplicants(String clubToken) {
ClubApply 는 Entity 아닌가요!?

2024-11-01 08:33 UTC, soeunnPark commented on api/src/main/java/org/badminton/api/interfaces/club/controller/ClubController.java
> +	@GetMapping("/{clubToken}/applicant")
applicants 가 더 적절할 것 같습니다!

2024-11-01 08:33 UTC, soeunnPark commented on api/src/main/java/org/badminton/api/interfaces/club/controller/ClubController.java
> +		List<ClubApply> clubApplies = clubFacade.readClubApplicants(clubToken);
여기서 반환되는 객체는 Info 여야 할 것 같아요!

2024-11-01 08:33 UTC, soeunnPark commented on api/src/main/java/org/badminton/api/interfaces/club/dto/ApplyClubRequest.java
> +	public ApplyClubCommand of() {
Dto가 도메인 계층 Command에 의존하게 하면 안될 것 같아요... !
Command 에서 Dto 를 받아 변환하는 방법 또는 Mapper를 사용하는 것이 적절할 것 같습니다!

2024-11-01 08:33 UTC, soeunnPark commented on api/src/main/java/org/badminton/api/interfaces/member/controller/MemberController.java
>  	}
CommonResponse 로 반환해주세요!

2024-11-01 08:33 UTC, soeunnPark commented on api/src/main/java/org/badminton/api/interfaces/member/dto/MemberMyPageResponse.java
> +				.collect(Collectors.toList());
이거 그냥 toList() 써도 동작하지 않아요?

2024-11-01 08:33 UTC, soeunnPark commented on domain/src/main/java/org/badminton/domain/domain/club/command/ApplyClubCommand.java
> +public record ApplyClubCommand(
Entity 이름은 ClubApply 인데 Command 이름은 ApplyClubCommand 에요. 하나로 통일하는게 어떨까요?

2024-11-01 08:33 UTC, soeunnPark commented on domain/src/main/java/org/badminton/domain/domain/clubmember/info/ApplyClubInfo.java
>  public record ApplyClubInfo(
Info 이름도 마찬가지입니다!

2024-11-04 01:28 UTC, soeunnPark approved these changes

2024-11-04 01:28 UTC, soeunnPark commented
ㅋㅋㅋㅋㅋ수고하셨습니다 ✨💤😴🍎

2024-11-04 01:32 UTC, merged