docs: error code 및 exception 수정
Kernel360/F2_PLAY_BADMINTON_BE pull request #41
Opened 2024-09-20 06:01 UTC by soeunnPark

## PR에 대한 설명 🔍

error code 및 custom exception 수정

## 변경된 사항 📝

에러 코드는 enum의 이름을 사용 (Integer -> String 타입으로 변경)
에러 코드를 도메인별로 분리하지 않고 한 곳에 정의 -> 에러 코드 인터페이스 제거
커스텀 예외 클래스는 에러 종류별로 정의

## PR에서 중점적으로 확인되어야 하는 사항

2024-09-20 10:24 UTC, LichKing-lee commented
1. 기본적으론 나누는 편인데 그렇다고 모든걸 다 나누면 너무 많이 나뉘게 되죠 예외의 중요도에 따라 비교적 덜 중요한 애들은 어느정도 합쳐서 쓰기도 합니다. 소은님이 작성해주신 `DuplicateException` 처럼요
2. 저는 클래스의 이름만으로 문제를 명확히 나타내는걸 선호해요
3. 예외 클래스 내에 들어가는 message 를 보통 ExceptionHandler 같은 곳에서 로그를 찍게되는데요. 저는 사용자에게 노출될 메시지보다 이슈가 생겼을때 로그로 문제를 파악하기 쉽게 하는거에 좀 더 초점이 맞춰져있는 것 같아요. 로그를 볼때 어떤 파라미터가 문제를 일으킨건지 빠르게 확인하기위해 동적 메시지를 쓰고, 최대한 상세한 타입명과 메시지를 남기는 편이에요

2024-09-20 10:31 UTC, LichKing-lee commented on badminton-api/src/main/java/org/badminton/api/club/validator/ClubValidator.java
> +			throw new DuplicationException(ErrorCode.RESOURCE_ALREADY_EXIST, ClubValidator.class.getSimpleName());
ExceptionHandler 에서 로그찍고 있지 않나요? 로그에는 stack trace 를 찍고있을텐데, 그러면 기본적으로 어느클래스의 몇 라인에서 예외가 발생했는지 알려주기때문에 이런 정보는 굳이 안넣어도 돼요

2024-09-20 10:31 UTC, LichKing-lee commented on badminton-api/src/main/java/org/badminton/api/exceptionhandler/BadmintonExceptionHandler.java
> +		var message = badmintonException.getErrorDetails();
아 여기서 로그를 안찍고있구나
```
log.error("예외발생", badmintonException);
```
요런식의 로그하나 찍어주세요~ 이 아래 메서드에도 마찬가지구요

2024-09-22 00:52 UTC, km2535 requested changes
코멘트 부분 수정 완료되면 다시 승인하겠습니다! 환경변수 파일은 꼭 내려주세요!

2024-09-22 00:52 UTC, km2535 commented on .env
.env는 내려 주세요!

2024-09-22 01:12 UTC, I-migi reviewed
확인했습니다 리뷰하신 거 수정하시고 merge 하셔도 될것 같아요!

2024-09-22 15:06 UTC, km2535 approved these changes
.env랑 코멘트 수정  후 머지 해주세용

2024-09-23 02:23 UTC, I-migi approved these changes
확인했습니다! 고생하셨어요! 😄

2024-09-23 02:26 UTC, merged

2024-09-23 03:30 UTC, soeunnPark commented on badminton-api/src/main/java/org/badminton/api/exceptionhandler/BadmintonExceptionHandler.java
> +		var message = badmintonException.getErrorDetails();
@LichKing-lee 네! 
```
예외 발생: RESOURCE_ALREADY_EXIST 예외 상세: 특정 리소스가 이미 존재합니다.[String: string]
```
이런 식으로 로그를 표시하고 있습니다..!!!!

2024-09-23 03:31 UTC, soeunnPark commented on badminton-api/src/main/java/org/badminton/api/club/validator/ClubValidator.java
> +			throw new DuplicationException(ErrorCode.RESOURCE_ALREADY_EXIST, ClubValidator.class.getSimpleName());
@LichKing-lee 네! 제거했습니다 👍

2024-09-23 03:38 UTC, soeunnPark commented
@LichKing-lee 주말에 다른 작업을 하느라 확인만 하고 리팩토링이 늦어졌습니다,, ㅠㅠ 죄송합니당..

제가 이해한 바로는,

1. 중요한 파라미터의 경우 타입을 보장하고, 더 구체적으로 예외를 표시하기 위해 나누는 것을 고려한다.
2. 덜 중요하다고 판단된다면, 적절하게 모으는 것을 고려한다.
3. 예외가 발생한 구체적인 원인을 개발자가 로그를 통해 확인해야 한다. 따라서 타입과 파라미터를 로그로 남길 필요가 있다.

와 같습니다!!

아직 clubName의 경우 VO로 타입을 만들지 않고 String 타입으로 존재합니다. 추후에 clubName이 중요하다고 판단되어 VO로 바꾼다면, 이를 아래와 같이 수정할 수 있을 것 같습니다 !

```
public class DuplicationException extends BadmintonException {
	public DuplicationException(ErrorCode errorCode, ClubName clubName) {
		super(errorCode, clubName);
	}
}
```

상황마다 중요도를 잘 판단하여 나눌지, 말지를 결정해야 한다는 점 이해했습니다!
말씀 주신 사항 반영하여 수정 완료했습니다 ㅎㅎ
자세한 답변 너무 감사드립니다 멘토님🥹👍👍👍👍👍✨

2024-09-23 05:20 UTC, LichKing-lee commented
@soeunnPark  zzzzㅋㅋㅋㅋㅋ 저한테 왜 죄송해요 해야할 시간에 안한것도 아닌데요
고생하셨고 더 궁금한 점있으면 좀따 많이 물어봐주세요~~

2024-09-23 07:48 UTC, soeunnPark commented
@LichKing-lee ㅎㅎㅎ 네에 !!! 감사합니다 ☺️